theme_layout_block:
  resource: \GravityCMS\CoreBundle\Controller\Api\LayoutBlockController
  type: rest
  prefix: /core

theme_layout:
  resource: \GravityCMS\CoreBundle\Controller\Api\LayoutController
  type: rest
  prefix: /core

theme_view:
  resource: \GravityCMS\CoreBundle\Controller\Api\ViewController
  type: rest
  prefix: /core


field:
  resource: \GravityCMS\CoreBundle\Controller\Api\FieldController
  type: rest
  prefix: /core

field_widget:
  resource: \GravityCMS\CoreBundle\Controller\Api\FieldWidgetController
  type: rest
  prefix: /core

field_display:
  resource: \GravityCMS\CoreBundle\Controller\Api\FieldDisplayController
  type: rest
  prefix: /core
