theme_list:
  path: /theme
  defaults: { _controller: GravityCMSCoreBundle:Theme:list }

theme_new:
  path: /theme/new
  defaults: { _controller: GravityCMSCoreBundle:Theme:new }

layout_list:
  path: /theme/layout
  defaults: { _controller: GravityCMSCoreBundle:Layout:list }

layout_new:
  path: /theme/layout/new
  defaults: { _controller: GravityCMSCoreBundle:Layout:new }

layout_edit:
  path: /theme/layout/{id}/edit
  defaults: { _controller: GravityCMSCoreBundle:Layout:edit }

layout_block_new:
  path: /theme/layout/{id}/block/new
  defaults: { _controller: GravityCMSCoreBundle:Layout:newBlock }

