index:
  path:     /
  defaults: { _controller: GravityCMSNodeBundle:ContentType:index }

content_type_new:
  path:     /content/new
  defaults: { _controller: GravityCMSNodeBundle:ContentType:new }

content_type_manage:
  path:     /content/manage
  defaults: { _controller: GravityCMSNodeBundle:ContentType:index }

content_type_edit:
  path:     /content/type/{type}/edit
  defaults: { _controller: GravityCMSNodeBundle:ContentType:edit }

content_type_edit_fields:
  path:     /content/type/{type}/fields
  defaults: { _controller: GravityCMSNodeBundle:ContentType:editFields }

content_type_edit_field:
  path:     /content/type/{type}/fields/{typeField}/edit
  defaults: { _controller: GravityCMSNodeBundle:ContentType:editField }

content_type_create_fields:
  path:     /content/type/{type}/fields/create
  defaults: { _controller: GravityCMSNodeBundle:ContentType:createFields, _method: POST }

content_type_edit_field_settings:
  path:     /content/type/{type}/fields/{typeField}/settings
  defaults: { _controller: GravityCMSNodeBundle:ContentType:editFieldSettings }

content_type_edit_form_view:
  path:     /content/type/{type}/form-view
  defaults: { _controller: GravityCMSNodeBundle:ContentType:editFormView }

content_type_edit_form_view_change:
  path:     /content/type/{type}/form-view/{typeField}/change
  defaults: { _controller: GravityCMSNodeBundle:ContentTypeField:changeFormView }

content_type_edit_form_view_settings:
  path:     /content/type/{type}/form-view/{typeField}/settings
  defaults: { _controller: GravityCMSNodeBundle:ContentTypeField:editFormViewSettings }

node_create_select:
  path: /node/create
  defaults: { _controller: GravityCMSNodeBundle:Admin\Node:newSelect }

node_index:
  path: /node/
  defaults: { _controller: GravityCMSNodeBundle:Admin\Node:index }

node_create:
  path: /node/{id}/create
  defaults: { _controller: GravityCMSNodeBundle:Admin\Node:new }
  requirements:
    id: \d+

node_edit:
  path: /node/{id}/edit
  defaults: { _controller: GravityCMSNodeBundle:Admin\Node:edit }
  requirements:
    id: \d+

routing_settings:
  path: /routing/settings
  defaults: { _controller: GravityCMSNodeBundle:Routing:settings }

routing_routes:
  path: /routing/routes
  defaults: { _controller: GravityCMSNodeBundle:Routing:routes }


routing_manage:
  path: /routing/manage
  defaults: { _controller: GravityCMSNodeBundle:Routing:manage }
