services:
  gravity_cms.entity_manager:
      class: GravityCMS\Component\Entity\EntityManager
#      tags:
#          - { name: gravity.entity }

  gravity_cms.form.view:
      class: GravityCMS\Component\Theme\Form\ViewForm
      arguments:
        - @gravity_cms.entity_manager
      tags:
        - { name: form.type, alias: gravity_cms_view }

  gravity.entity_service.field:
    class: GravityCMS\CoreBundle\Entity\Service\FieldEntityService
    arguments:
      - @doctrine.orm.default_entity_manager
      - @gravity_cms.field_manager

  gravity.entity_service.field_widget:
    class: GravityCMS\CoreBundle\Entity\Service\FieldWidgetEntityService
    arguments:
      - @doctrine.orm.default_entity_manager
      - @gravity_cms.field_manager

  gravity.entity_service.field_display:
    class: GravityCMS\CoreBundle\Entity\Service\FieldDisplayEntityService
    arguments:
      - @doctrine.orm.default_entity_manager
      - @gravity_cms.field_manager
