services:

  #
  # Fields
  gravity.field.number:
    class: GravityCMS\CoreBundle\Field\Number\NumberField
    tags:
      - { name: gravity.field }

  gravity.field.number.display.number:
    class: GravityCMS\CoreBundle\Field\Number\Display\Number\NumberDisplay
    tags:
      - { name: gravity.field.display }

  gravity.field.number.widget.number_box:
    class: GravityCMS\CoreBundle\Field\Number\Widget\NumberBox\NumberBoxWidget
    tags:
      - { name: gravity.field.widget }
