
services:
  #
  # Form Types
  gravity_cms.form.type.hidden_entity:
      class: GravityCMS\Component\Form\Type\HiddenEntityIdType
      tags:
          - { name: form.type, alias: hidden_entity }

  #
  # AutoComplete
  gravity.cms.auto_complete_manager:
    class: GravityCMS\Component\Form\AutoComplete\AutoCompleteManager

  gravity.cms.form.type.auto_complete:
      class: GravityCMS\Component\Form\Type\AutoCompleteType
      arguments:
        - @gravity.cms.auto_complete_manager
        - @router.default
      tags:
          - { name: form.type, alias: auto_complete }

  gravity_cms.form.type.basic_route:
      class: GravityCMS\Component\Form\Type\BasicRouteType
      tags:
          - { name: form.type, alias: basic_route }

  gravity_cms.form.type.toggle:
      class: GravityCMS\Component\Form\Type\ToggleType
      tags:
          - { name: form.type, alias: toggle }

  gravity_cms.field.form.type.field_configuration:
      class: GravityCMS\Component\Field\Form\Type\FieldConfigurationType
      tags:
          - { name: form.type, alias: field_configuration }
