parameters:
  gravity_cms.routing.module_loader.class:  GravityCMS\Component\Router\ModuleLoader
  gravity_cms.routing.api_loader.class:     GravityCMS\Component\Router\ApiLoader
  gravity_cms.routing.web_loader.class:     GravityCMS\Component\Router\WebLoader
  gravity_cms.routing.admin_loader.class:   GravityCMS\Component\Router\AdminLoader

services:
  gravity_cms.routing.module_loader:
    class: %gravity_cms.routing.module_loader.class%
    tags:
      - { name: routing.loader }

  gravity_cms.routing.api_loader:
    class: %gravity_cms.routing.api_loader.class%
    arguments:
      - @file_locator
    tags:
      - { name: routing.loader }

  gravity_cms.routing.web_loader:
    class: %gravity_cms.routing.web_loader.class%
    tags:
      - { name: routing.loader }

  gravity_cms.routing.admin_loader:
    class: %gravity_cms.routing.admin_loader.class%
    tags:
      - { name: routing.loader }

  gravity_cms.routing.route_provider:
    class: GravityCMS\Component\Router\GravityRouteProvider
    arguments:
      - @doctrine.orm.default_entity_manager
