parameters:
  # Theming
  gravity_cms.theme_manager.class:  GravityCMS\Component\Theme\ThemeManager
  gravity_cms.theme_loader.class:   GravityCMS\Component\Theme\Twig\Loader\ThemeLoader

  templating.form_template_manager.class: GravityCMS\Component\Theme\Form\FormTemplateManager

  # override the asset factory
  assetic.asset_factory.class:        GravityCMS\Component\Theme\Assetic\Factory\GravityAssetFactory
  gravity_cms.asset_manager.class:    GravityCMS\Component\Theme\Assetic\GravityAssetManager

  gravity_cms.twig.assets_extension:  GravityCMS\Component\Theme\Twig\CoreExtension

services:

  #
  # Theming
  gravity_cms.theme_manager:
    class: %gravity_cms.theme_manager.class%

  twig.loader.theme_loader:
    class: %gravity_cms.theme_loader.class%
    arguments:
      - @gravity_cms.theme_manager
      - @templating.locator.theme_filesystem_locator
      - @templating.name_parser
    tags:
      - { name: twig.loader }

  #
  # Template loader!
  templating.locator.theme_locator:
    class: GravityCMS\Component\Theme\Templating\Locator\ThemeLocator
    arguments:
      - @gravity_cms.theme_manager

  templating.locator.theme_filesystem_locator:
    class: %templating.locator.class%
    arguments:
      - @templating.locator.theme_locator
      - %kernel.cache_dir%

  templating.loader.theme_loader:
    class: %templating.loader.filesystem.class%
    arguments:
      - @templating.locator.theme_locator

  templating.form_template_manager:
    class: %templating.form_template_manager.class%

  # Default Theme
  gravity_cms.theme.gravity_admin:
    class: GravityCMS\Component\Theme\Theme\GravityAdmin\GravityAdminTheme
    tags:
      - { name: gravity_cms.theme, alias: gravity_admin }

  #
  # Asset manager
  gravity_cms.asset_manager:
    class: %gravity_cms.asset_manager.class%

  #
  # Twig Functions for plugins
  gravity_cms.twig.assets_core_extension:
    class: %gravity_cms.twig.assets_extension%
    arguments:
      - @gravity_cms.asset_manager
    tags:
      - { name: twig.extension }

  #
  # Views
  gravity_cms.view_manager:
    class: GravityCMS\Component\View\ViewManager

  gravity_cms.theme.layout_manager:
    class: GravityCMS\Component\View\Layout\LayoutManager
    arguments:
      - @gravity_cms.config_manager
      - @gravity_cms.theme.block_manager

  #
  # Layout Positions
  gravity_cms.theme.layout.position.header:
    class: GravityCMS\Component\View\Layout\Position\HeaderPosition
    tags:
      - { name: layout.position }

  gravity_cms.theme.layout.position.content:
    class: GravityCMS\Component\View\Layout\Position\ContentPosition
    tags:
      - { name: layout.position }

  gravity_cms.theme.layout.position.footer:
    class: GravityCMS\Component\View\Layout\Position\FooterPosition
    tags:
      - { name: layout.position }

  gravity_cms.theme.layout.position.navigation:
    class: GravityCMS\Component\View\Layout\Position\NavigationPosition
    tags:
      - { name: layout.position }

  gravity_cms.theme.form.layout:
    class: GravityCMS\Component\View\Form\LayoutForm
    tags:
      - { name: form.type, alias: gravity_cms_layout }


  gravity_cms.theme.form.layout_block:
    class: GravityCMS\Component\View\Form\LayoutBlockForm
    arguments:
      - @gravity_cms.theme.block_manager
    tags:
      - { name: form.type, alias: gravity_cms_layout_block }

  gravity_cms.theme.form.ayout_layout_position_block:
      class: GravityCMS\Component\View\Form\LayoutLayoutPositionBlockForm
      arguments:
        - @doctrine.orm.default_entity_manager
      tags:
        - { name: form.type, alias: gravity_cms_layout_layout_position_block }

  #
  # Blocks
  gravity_cms.theme.block_manager:
    class: GravityCMS\Component\View\Block\BlockManager
    arguments:
      - @gravity_cms.config_manager

  gravity_cms.theme.block.text:
    class: GravityCMS\CoreBundle\View\Block\Text\TextBlock
    tags:
      - { name: layout.block }
