theme:
  title: Themes
  icon: paint-brush
  items:
    themes:
      route: gravity_cms_admin_theme_list
      title: Themes
      description: ~
    layouts:
      route: gravity_cms_admin_layout_list
      title: Layouts
      description: ~
    views:
      route: gravity_cms_admin_theme_view_list
      title: Views
      description: ~
