imports:
    - { resource: services/module.yml }
    - { resource: services/theme.yml }
    - { resource: services/router.yml }
    - { resource: services/menu.yml }
    - { resource: services/forms.yml }
    - { resource: services/entity.yml }
    - { resource: services/editor.yml }

parameters: ~

services:
  gravity_cms.config_manager:
    class: GravityCMS\Component\Configuration\ConfigurationManager
    arguments:
      - @doctrine.orm.default_entity_manager

  gravity_cms.content_type_manager:
    class: GravityCMS\Component\ContentType\ContentTypeManager
    arguments:
      - @gravity_cms.config_manager

  gravity_cms.field_manager:
    class: GravityCMS\Component\Field\FieldManager
